apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mqj7017as-python
  janus-idp.io/tekton: mqj7017as-python
  backstage.io/kubernetes-id: mqj7017as-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mqj7017as-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
